# Generated by Django 3.1.4 on 2021-06-22 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20210622_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achieve',
            name='club',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='club',
        ),
        migrations.RemoveField(
            model_name='post',
            name='club',
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.RemoveField(
            model_name='member',
            name='club',
        ),
        migrations.AddField(
            model_name='member',
            name='club',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='club.club'),
            preserve_default=False,
        ),
    ]
