# Generated by Django 3.1.4 on 2021-06-22 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_auto_20210622_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='achieve',
            name='club',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='club.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='club',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='club.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='club',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='club.club'),
            preserve_default=False,
        ),
    ]
